name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag certbot-dns-aly:$(date)


    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Push Docker image
      run: |
        docker tag certbot-dns-aly:$(date) ${{ secrets.DOCKER_HUB_USERNAME }}/certbot-dns-aly:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/certbot-dns-aly:latest
